import Header from '@/components/Header'
import './globals.css'
import PromptInput from '@/components/PromptInput'
import ClientProvider from '@/components/ClientProvider'


export const metadata = {
  title: 'AI Image Generator',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='pb-20'>
        <ClientProvider>
          <Header />
          <PromptInput />
          {children}
        </ClientProvider>
      </body>
    </html >
  )
}
